language: python
sudo: false
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27-django1.8
    - python: "3.4"
      env: TOXENV=py34-django1.8
    - python: "2.7"
      env: TOXENV=py27-django1.9
    - python: "3.5"
      env: TOXENV=py35-django1.9
    - python: "2.7"
      env: TOXENV=py27-django1.10
    - python: "3.5"
      env: TOXENV=py35-django1.10
    - python: "2.7"
      env: TOXENV=py27-django1.11
    - python: "3.6"
      env: TOXENV=py36-django1.11
    - python: "3.5"
      env: TOXENV=py35-django2.0
    - python: "3.5"
      env: TOXENV=py35-django2.1
    - python: "3.6"
      env: TOXENV=py36-django2.2
      dist: xenial  # For SQLite 3.8.3 or later
    - python: "3.7"
      env: TOXENV=py37-djangomaster
      dist: xenial  # For Python 3.7
  allow_failures:
    - env: TOXENV=py37-djangomaster
install:
    - pip install tox
script:
    - tox
